language: node_js

node_js:
  - "8.13.0"

notifications:
  webhooks: https://www.travisbuddy.com

cache: npm

branches:
  only:
    - master

before_script:
  - npm install -g firebase-tools

script:
  - npm run-script build

after_success:
  - firebase deploy --token $FIREBASE_TOKEN
